server:
  port: 8010

spring:
  kafka:
    properties:
      bootstrap-servers: "localhost:9092"
      auto:
        register:
          schemas: true
      schema:
        registry:
          url: "http://127.0.0.1:8081"

    producer:
      client-id: "produtor-sistema"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"

avro:
  topic:
    name: "Topic_Mensagem_Envio_Stock"

auto:
  create:
    topics:
      enable: true