server:
  port: 8010

spring:
  kafka:
    producer:
      bootstrap-servers: "localhost:9092"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        auto:
          register:
            schemas: true
        schema:
          registry:
            url: "http://127.0.0.1:8081"
