server:
  port: 8110

spring:
  kafka:
    properties:
      schema:
        registry:
          url: "http://127.0.0.1:8081"
      specific:
        avro:
          reader: "true"

    consumer:
      client-id: "consumidor-sistema"
      group-id: "grp-comunicacao-sistema-a"
      autoOffsetReset: "earliest"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"

avro:
  topic:
    name: "Topic_Mensagem_Envio_Stock"

auto:
  create:
    topics:
      enable: true